trigger: none
phases:
 - template: ../phases/build-all.yml
   parameters:
     repo: dotnet-framework
     matrixWindowsLtsc2016Amd64:
       Build_3_5:
         buildPath: 3.5-*
         osVersion: windowsservercore-ltsc2016
       Build_4_6_2:
         buildPath: 4.6.2-*
         osVersion: windowsservercore-ltsc2016
       Build_4_7:
         buildPath: 4.7-*
         osVersion: windowsservercore-ltsc2016
       Build_4_7_1:
         buildPath: 4.7.1-*
         osVersion: windowsservercore-ltsc2016
       Build_4_7_2:
         buildPath: 4.7.2-*
         osVersion: windowsservercore-ltsc2016
     matrixWindows1709Amd64:
       Build_3_5:
         buildPath: 3.5-*
         osVersion: windowsservercore-1709
       Build_4_7_1:
         buildPath: 4.7.1-*
         osVersion: windowsservercore-1709
       Build_4_7_2:
         buildPath: 4.7.2-*
         osVersion: windowsservercore-1709
     matrixWindows1803Amd64:
       Build_3_5:
         buildPath: 3.5-*
         osVersion: windowsservercore-1803
       Build_4_7_2:
         buildPath: 4.7.2-*
         osVersion: windowsservercore-1803
